services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - innovationlab
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-api:
    build:
      context: .
      dockerfile: InnovationLab.Auth/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    networks:
      - innovationlab

  landing-api:
    build:
      context: .
      dockerfile: InnovationLab.Landing/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
    networks:
      - innovationlab

volumes:
  db_data:

networks:
  innovationlab:
    driver: bridge
